### ISSUE TITLE
Initialization fails with Error: TypeError: Object #<Object> has no method 'describe_'

### ISSUE THREAD

**Issue by PhilippCh** [Updater/jasmine-fail-fast#4]
I've added the lib via protractor, but upon starting I receive the following error message and my tests immediately quit:

```
[launcher] Error: TypeError: Object #<Object> has no method 'describe_'
    at jasmine.Env.describe (/Users/philipp/entwicklung/sptablet-webapps/voucher-webapp/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/minijasminenode/lib/jasmine-1.3.1.js:898:15)
    at [object Object].<anonymous> (/Users/philipp/entwicklung/sptablet-webapps/voucher-webapp/node_modules/jasmine-fail-fast/dist/jasmine-fail-fast.js:57:26)
    at [object Object].wrapper [as describe] (/Users/philipp/entwicklung/sptablet-webapps/voucher-webapp/node_modules/jasmine-fail-fast/node_modules/lodash/index.js:3592:19)
    at Object.exports.executeSpecs (/Users/philipp/entwicklung/sptablet-webapps/voucher-webapp/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/minijasminenode/lib/index.js:134:18)
    at /Users/philipp/entwicklung/sptablet-webapps/voucher-webapp/node_modules/grunt-protractor-runner/node_modules/protractor/lib/frameworks/jasmine.js:82:14
    at Function.promise (/Users/philipp/entwicklung/sptablet-webapps/voucher-webapp/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/q/q.js:650:9)
    at /Users/philipp/entwicklung/sptablet-webapps/voucher-webapp/node_modules/grunt-protractor-runner/node_modules/protractor/lib/frameworks/jasmine.js:63:14
    at _fulfilled (/Users/philipp/entwicklung/sptablet-webapps/voucher-webapp/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/q/q.js:797:54)
    at self.promiseDispatch.done (/Users/philipp/entwicklung/sptablet-webapps/voucher-webapp/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/q/q.js:826:30)
    at Promise.promise.promiseDispatch (/Users/philipp/entwicklung/sptablet-webapps/voucher-webapp/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/q/q.js:759:13)
[launcher] Process exited with error code 100
```

**Comment by pmowrer** [comment]
Possibly there's a conflict with some other customization of Jasmine. Are you or some 3rd party code overriding `jasmine.getEnv().describe`?

**Comment by pmowrer** [comment]
Closing due to lack of information.

**Comment by skilesare** [comment]
I had this same issue.  A little more info:

I have two specs in my spec folder, A.js and B.js.   When I include the code

var failFast = require('jasmine-fail-fast');
jasmine.getEnv().addReporter(failFast.init());

in both, I get this error:

Exception loading: /Users/austin/Documents/Dropbox/development/Rivvir/BIM2017/spec/configuration_spec.js
TypeError: this.describe_ is not a function
  at jasmine.Env.describe (/Users/austin/Documents/Dropbox/development/Rivvir/BIM2017/node_modules/jasmine-node/lib/jasmine-node/jasmine-1.3.1.js:869:15)
  at .<anonymous> (/Users/austin/Documents/Dropbox/development/Rivvir/BIM2017/node_modules/jasmine-fail-fast/dist/jasmine-fail-fast.js:57:26)
  at wrapper [as describe] (/Users/austin/Documents/Dropbox/development/Rivvir/BIM2017/node_modules/lodash/index.js:3592:19)
  at describe (/Users/austin/Documents/Dropbox/development/Rivvir/BIM2017/node_modules/jasmine-node/lib/jasmine-node/jasmine-1.3.1.js:629:27)
  at Object.<anonymous> (/Users/austin/Documents/Dropbox/development/Rivvir/BIM2017/spec/configuration_spec.js:11:3)
  at Object.<anonymous> (/Users/austin/Documents/Dropbox/development/Rivvir/BIM2017/spec/configuration_spec.js:40:4)
  at Module._compile (module.js:541:32)
  at Object.Module._extensions..js (module.js:550:10)

If I just have one file it works fine!

I tried moving the code to helpers.js file and it caused the same issue.  Something about running the code twice causes some issues.  I suspect maybe too many reporters?

I'm using jasmine-node so maybe that is where the conflict lies?

**Comment by pmowrer** [comment]
This project has never been tested to work with a `jasmine` version other than 2.x. `jasmine-node` uses `jasmine` 1.3.1, a very old version jasmine that predates this library. I'd recommend moving away from `jasmine-node`... it appears to be a dead project.
